name: Docker

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use (defaults to "test")'
        default: 'test'

permissions: {}

env:
  VERSION: 0.0.1
  IMAGE_NAME: talos_af
  DOCKER_DEV: australia-southeast1-docker.pkg.dev/cpg-common/images-dev
  DOCKER_MAIN: australia-southeast1-docker.pkg.dev/cpg-common/images

jobs:
  docker-dev:
    name: Build & Push to Dev
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch' && github.ref_name != 'main')
    environment: development
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash -l {0}
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - uses: actions/checkout@v4

      - id: 'google-cloud-auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.DEV_IMG_DEPLOYER_POOL}}
          service_account: ${{ secrets.DEV_IMG_DEPLOYER_SA }}

      - name: set up gcloud sdk
        uses: google-github-actions/setup-gcloud@v2

      - name: gcloud docker auth
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: build
        run: |
          docker build . -f Dockerfile --tag $IMAGE_NAME:${{ github.sha }}

      - name: Push Pull Request build
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $DOCKER_DEV/$IMAGE_NAME:PR_${{github.event.number}}
          docker push $DOCKER_DEV/$IMAGE_NAME:PR_${{github.event.number}}

      - name: Push manually triggered dev build
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref_name != 'main' }}
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $DOCKER_DEV/$IMAGE_NAME:${{github.event.inputs.tag}}
          docker push $DOCKER_DEV/$IMAGE_NAME:${{github.event.inputs.tag}}

  docker-prod:
    name: Build & Push to Prod
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    environment: production
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash -l {0}
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - uses: actions/checkout@v4

      - id: 'google-cloud-auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.PROD_IMG_DEPLOYER_POOL}}
          service_account: ${{ secrets.PROD_IMG_DEPLOYER_SA }}

      - name: set up gcloud sdk
        uses: google-github-actions/setup-gcloud@v2

      - name: gcloud docker auth
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: build
        run: |
          docker build . -f Dockerfile --tag $IMAGE_NAME:${{ github.sha }}

      - name: Push to production
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $DOCKER_MAIN/$IMAGE_NAME:$VERSION
          docker push $DOCKER_MAIN/$IMAGE_NAME:$VERSION